// autogenerated by numTempl.py. DO NOT EDIT !!!!!!
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/event.h>

#include "drv.h"
#include "sysc.h"

int getStdFile(int typ)
{
    int fd, pipes[2];

    fd = -1;
    switch(typ) {
#define F(n, fn, flg) case n: fd = open(fn, flg); break;
    F(0, "/", O_RDONLY);
#define S(n, a,b,c) case n: fd = socket(a, b, c); break;
    S(1, AF_INET, SOCK_STREAM, 0);
    S(2, AF_INET, SOCK_DGRAM, 0);
    S(3, AF_UNIX, SOCK_STREAM, 0);
    S(4, AF_UNIX, SOCK_DGRAM, 0);

    case 5: 
        if(pipe(pipes) == -1) return -1;
        fd = pipes[0];
        break;
    case 6:
        if(pipe(pipes) == -1) return -1;
        fd = pipes[1];
        break;

    S(7, AF_UNIX, SOCK_STREAM, 0);
    S(8, AF_UNIX, SOCK_DGRAM, 0);
    S(9, AF_UNIX, SOCK_SEQPACKET, 0);
    S(10, AF_UNIX, SOCK_RAW, 0);
    S(11, AF_UNIX, SOCK_RDM, 0);
    S(12, AF_INET, SOCK_STREAM, 0);
    S(13, AF_INET, SOCK_DGRAM, 0);
    S(14, AF_INET, SOCK_SEQPACKET, 0);
    S(15, AF_INET, SOCK_RAW, 0);
    S(16, AF_INET, SOCK_RDM, 0);
    S(17, AF_INET6, SOCK_STREAM, 0);
    S(18, AF_INET6, SOCK_DGRAM, 0);
    S(19, AF_INET6, SOCK_SEQPACKET, 0);
    S(20, AF_INET6, SOCK_RAW, 0);
    S(21, AF_INET6, SOCK_RDM, 0);
    S(22, AF_IPX, SOCK_STREAM, 0);
    S(23, AF_IPX, SOCK_DGRAM, 0);
    S(24, AF_IPX, SOCK_SEQPACKET, 0);
    S(25, AF_IPX, SOCK_RAW, 0);
    S(26, AF_IPX, SOCK_RDM, 0);
    S(27, AF_APPLETALK, SOCK_STREAM, 0);
    S(28, AF_APPLETALK, SOCK_DGRAM, 0);
    S(29, AF_APPLETALK, SOCK_SEQPACKET, 0);
    S(30, AF_APPLETALK, SOCK_RAW, 0);
    S(31, AF_APPLETALK, SOCK_RDM, 0);

#define SP(n, f, ty, idx) case n: socketpair(f, ty, 0, pipes); fd = pipes[idx]; break
    SP(32, AF_UNIX, SOCK_STREAM, 0);
    SP(33, AF_UNIX, SOCK_STREAM, 1);
    SP(34, AF_UNIX, SOCK_DGRAM, 0);
    SP(35, AF_UNIX, SOCK_DGRAM, 1);
    SP(36, AF_UNIX, SOCK_SEQPACKET, 0);
    SP(37, AF_UNIX, SOCK_SEQPACKET, 1);

    case 38:
        fd = kqueue();
        break;

    default:
        // XXX nonblocking sockets?
        // XXX AF_NETLINK x (DGRAM,RAW) x protonr 0..22
        // XXX (INET, INET6) x SOCK_RAW x protonr 0..256
        // XXX PACKET X (DGRAM, RAW) x htons(rawtypes)
        // XXX weird files from /dev, /proc, /sys, etc..
        return -1;
    }
    return fd;
}

