#!/usr/bin/env python2.7
import sys

NUM = '$NUM'
cnt = iter(xrange(10000));

sys.stdout.write("// autogenerated by numTempl.py. DO NOT EDIT !!!!!!\n")
for l in sys.stdin :
    if NUM in l :
        l = l.replace(NUM, str(cnt.next()))
    sys.stdout.write(l)
